package de.sdr.astro.cat.forms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import de.sdr.astro.cat.config.Config;

import javax.swing.*;
import java.awt.*;

public class ConfigPanel {

    private JPanel topPanel;
    private JTabbedPane tabbedPaneEquipment;
    private final ConfigEquipmentPanel configEquipmentPanel;
    private final ConfigProfilePanel configProfilePanel;

    public JPanel getTopPanel() {
        return topPanel;
    }

    public ConfigPanel() {
        configEquipmentPanel = new ConfigEquipmentPanel();
        configProfilePanel = new ConfigProfilePanel();
        tabbedPaneEquipment.addTab(Config.getInstance().getL10n().getString("common_my.equipment"), configEquipmentPanel.getTopPanel());
        tabbedPaneEquipment.addTab(Config.getInstance().getL10n().getString("common_profiles"), configProfilePanel.getTopPanel());

        configEquipmentPanel.activatePanel();
        tabbedPaneEquipment.addChangeListener(changeEvent -> {
            switch (tabbedPaneEquipment.getSelectedIndex()) {
                case 0:
                    configEquipmentPanel.activatePanel();
                    break;
                case 1:
                    configProfilePanel.activatePanel();
                    break;

            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        topPanel = new JPanel();
        topPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        topPanel.setMinimumSize(new Dimension(-1, -1));
        topPanel.setPreferredSize(new Dimension(800, 480));
        tabbedPaneEquipment = new JTabbedPane();
        tabbedPaneEquipment.setName("");
        tabbedPaneEquipment.setTabPlacement(1);
        topPanel.add(tabbedPaneEquipment, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPanel;
    }

}
